# Default values for gotosocial.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: null # chart-example.local
applicationName: gotosocial
landingPageUser: ""
acountDomain: ""
timezone: "UTC"


log:
  level: info
  dbQueries: false
  clientIP: true
  timestampFormat: 02/01/2006 15:04:05.000

db:
  type: "sqlite"
  address: /gotosocial/storage/sqlite.db
tls:
  enabled: false
  email: ""

# define arbitrary environment variables for the GoToSocial application
# this is especially useful if you want to leverage GoToSocial functionality
# that is not yet supported by "normal" chart values (please open an issue/PR if you'd like "real" support) 
env:
#  FOO: bar

image:
  repository: superseriousbusiness/gotosocial
  pullPolicy: IfNotPresent
  tag: latest
  pullSecrets: []

storage:
  local:
    enabled: true
    claimName: null
    accessModes:
    - ReadWriteOnce
    labels: {}
    class:
    annotations:
      helm.sh/resource-policy: keep
    size: 10Gi
  s3: #todo no implemented yet
    enabled: false



nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  # - host: chart-example.local
  #   paths:
  #   - path: /
  #     pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #    - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
