{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "gotosocial.datapvc" . }}
  annotations:
    {{- .Values.persistence.annotations | toYaml | nindent 4}}
spec:
  accessModes:
    {{- .Values.persistence.accessModes | toYaml | nindent 4 }}
  volumeMode: Filesystem
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}