apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotosocial.fullname" . }}
  labels:
    {{- include "gotosocial.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gotosocial.selectorLabels" . | nindent 4 }}
