name: Build & Test Chart
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v3
    - uses: helm/kind-action@v1.8.0
    - name: template test
      run: |
        for file in test-values/*; do
          echo "############## template $file ###############"
          helm template --debug --validate gts-test . -f $file
          echo "#############################################"
        done
    - name: install test
      run: |
        for file in test-values/*; do
          echo "############## install $file ###############"
          helm install --wait gts-test . -f $file
          helm uninstall --wait gts-test
          echo "#############################################"
        done 
