name: Build & Test Chart

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    - name: install unittest plugin
      run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
    - uses: helm/kind-action@v1.8.0
    - name: unit tests
      run: |
        helm unittest charts/gotosocial
    - name: template tests
      run: |
        for file in test-values/*; do
          echo "############## template $file ###############"
          helm template --debug --validate gts-test charts/gotosocial -f $file
          echo "#############################################"
        done
    - name: integration tests
      run: |
        for file in test-values/*; do
          echo "############## install $file ################"
          helm install --wait gts-test charts/gotosocial -f $file
          helm uninstall --wait gts-test
          echo "#############################################"
        done 
